### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by HwangGwa** [mostm/pyqiwi#1]
import pyqiwi
wallet = pyqiwi.Wallet(token='',number='')
balance = wallet.balance(643)

Sometimes above code will raise this error:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/www/venv/lib/python3.4/site-packages/pyqiwi/__init__.py", line 91, in balance
    return account.balance.get('amount')
AttributeError: 'NoneType' object has no attribute 'get'
`

I don't know whether it's network problem

**Comment by mostm** [comment]
I fixed it in new release 2.0.6, and added new documentation on why this happen
