### ISSUE TITLE
TypeError: not a valid non-string sequence or mapping object

### ISSUE THREAD

**Issue by aesto1** [mostm/pyqiwi#15]
**Python 3.6.5**

> [14/Jul/2018 00:00:17] Traceback (most recent call last): File "E:\\Python \\lib\\urllib\\parse.py", line 856, in urlencode  raise TypeError TypeError During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\\Users\\Fin\\Desktop\\PyProject\\Web\\cgi-bin\\processing.py", line 53, in <module>    paylink = pyqiwi.generate_form_link(pid=99, account=79094167269, amount=50, comment="test")  File "E:\\Python\\lib\\site-packages\\pyqiwi\\__init__.py", line 470, in
> generate_form_link   params[\'comment\'] = urlencode(comment)  File "E:\\Python\\lib\\ urllib\\parse.py", line 864, in urlencode    "or mapping object").with_traceback(tb)  File "E:\\Python\\lib\\urllib\\parse.py", line 856, in urlencode    raise TypeError TypeError: not a valid non-string sequence or mapping object'
> 127.0.0.1 - - [14/Jul/2018 00:00:17] CGI script exit status 0x1

**Comment by gil9red** [comment]
https://ru.stackoverflow.com/a/856023/201445

**Comment by mostm** [comment]
Это было пофикшено в последнем релизе, спасибо за созданный issue @aesto1, и за подробный ответ @gil9red.
