### ISSUE TITLE
Help with install and launch this

### ISSUE THREAD

**Issue by SaintStealler** [mostm/pyqiwi#18]
I had clone files and i dont understand how to install them. I dont understand where to write this - "python setup.py install", in cmd? or what? in cmd i have this - (null): can't open file 'setup.py': [Errno 2] No such file or directory. 
Next. Where i can make a new project? i dont understand where to write "import pyqiwi"
Help me pls

**Comment by mostm** [comment]
Just use `pip install qiwipy` from `cmd` and `import pyqiwi` in your python files/console.
