### ISSUE TITLE
AttributeError: module 'pyqiwi' has no attribute 'Wallet'

### ISSUE THREAD

**Issue by Disaxy** [mostm/pyqiwi#19]
import pyqiwi
from config import QIWI_TOKEN, NUMBER
wallet = pyqiwi.Wallet(QIWI_TOKEN, NUMBER)
print(wallet.balance())

Traceback (most recent call last):
  File "qiwi_wallet.py", line 15, in <module>
    wallet = pyqiwi.Wallet(QIWI_TOKEN, NUMBER)
AttributeError: module 'pyqiwi' has no attribute 'Wallet'

**Comment by Disaxy** [comment]
по ощущениям не хватает этого файла https://pyqiwi.readthedocs.io/ru/latest/_modules/pyqiwi.html#Wallet
программирую не давно, строго не судите если что, просто зашел в папку с этим модулем, и этого куска кода я там не нашел совсем, пробывал сам добавить туда но не помогает

**Comment by mostm** [comment]
Вы установили при помощи `pip` пакет `qiwipy`, верно?
Установленные пакеты можно проверить командой `pip list`
В списке должен присутствовать пакет `qiwipy` версии `2.1.4`(последняя на данный момент версия)
Если версия не совпадает, советую обновить при помощи `pip install -U qiwipy`
Если пакета нет, установите при помощи `pip install qiwipy`

**Comment by Disaxy** [comment]
Все разобрался, спасибо.
