### ISSUE TITLE
Не выдаётся чек

### ISSUE THREAD

**Issue by ravensoracle** [mostm/pyqiwi#21]
Wallet().cheque зависает на 5 секунд и выдаёт ошибку о недуачном парсинге JSON.

**Comment by mostm** [comment]
Если это возможно, могли бы вы указать весь стектрейс, вместе со входными данными?

**Comment by ravensoracle** [comment]
Там киви выдает raw изображение, а библиотека скачивает это всё долго и пытается json'ом спарсить.

**Comment by mostm** [comment]
Сделал прямую отдачу того что передает Qiwi. Что там будет - неизвестно, и проверок ошибок внутри ответа - нет.
