### ISSUE TITLE
Несоответствие названия sum (действительное _sum) в types.Payment

### ISSUE THREAD

**Issue by 3xp0rt** [mostm/pyqiwi#29]
if pyqiwi.types.Payment(comment='Привет!', sum='1'):
TypeError: __init__() got an unexpected keyword argument 'sum'

**Comment by mostm** [comment]
На данный момент используй `_sum` вместо `sum`
В будущей версии стоит подправить на `sum`...

**Comment by 3xp0rt** [comment]
> На данный момент используй `_sum` вместо `sum`
> В будущей версии стоит подправить на `sum`...

Спасибо за ответ. Я то думал уже свою библиотеку писать, из-за этого 😂.
