### ISSUE TITLE
Нет комментария: generate_form_link

### ISSUE THREAD

**Issue by ShadXst** [mostm/pyqiwi#36]
Пример вызова:
`
pyqiwi.generate_form_link(pid='99', account='79505504545', amount=10, comment='some_comment', blocked=['sum', 'account', 'comment'], account_type=0)`

Результат:
.../payment/form/99?currency=643&amount=10&extra%5B%27account%27%5D=79505504545&blocked%5B0%5D=sum&blocked%5B1%5D=account&blocked%5B2%5D=comment

В результате, при переходе по ссылке, поле 'Комментарий к переводу' оказывается пустым и не заблокированным.

**Comment by mostm** [comment]
Данная проблема была исправлена следующим PR: https://github.com/mostm/pyqiwi/pull/38
Спасибо за отправленный issue :)
